#!/usr/bin/env python
"""
Copyright (C) 2010-2011 Mikael W. Ibsen
Some portions Copyright (C) 2011-2016 Casper Steinmann
"""
# let us first consider that the user has set up the
# PYTHONPATH environment variables correctly
try:
    from fragit.fragit_exceptions import OBNotFoundException
except ImportError:
    # if not, let us exit in a clean way
    print("Error: Could not start FragIt.")
    print("Please add the custom installation path to the PYTHONPATH environment variable.")
    exit()

try:
    from fragit.cmdline import main
except OBNotFoundException:
    print("Error: OpenBabel could not be loaded.")
    print("Please make sure OpenBabel has been installed with python bindings.")
    exit()

if __name__ == '__main__':
    main()
